/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as TicketBookingIdRouteImport } from './routes/ticket.$bookingId'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ApiBookingsRouteImport } from './routes/api.bookings'
import { Route as ApiBookingsBookingIdRouteImport } from './routes/api.bookings.$bookingId'
import { Route as ApiMpesaInitiateRouteImport } from './routes/api.mpesa.initiate'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api.mpesa.callback'

const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketBookingIdRoute = TicketBookingIdRouteImport.update({
  id: '/ticket/$bookingId',
  path: '/ticket/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsBookingIdRoute = ApiBookingsBookingIdRouteImport.update({
  id: '/api/bookings/$bookingId',
  path: '/api/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaInitiateRoute = ApiMpesaInitiateRouteImport.update({
  id: '/api/mpesa/initiate',
  path: '/api/mpesa/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/organizers': typeof OrganizersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket/$bookingId': typeof TicketBookingIdRoute
  '/api/events': typeof ApiEventsRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/bookings/$bookingId': typeof ApiBookingsBookingIdRoute
  '/api/mpesa/initiate': typeof ApiMpesaInitiateRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/organizers': typeof OrganizersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket/$bookingId': typeof TicketBookingIdRoute
  '/api/events': typeof ApiEventsRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/bookings/$bookingId': typeof ApiBookingsBookingIdRoute
  '/api/mpesa/initiate': typeof ApiMpesaInitiateRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/organizers': typeof OrganizersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket/$bookingId': typeof TicketBookingIdRoute
  '/api/events': typeof ApiEventsRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/bookings/$bookingId': typeof ApiBookingsBookingIdRoute
  '/api/mpesa/initiate': typeof ApiMpesaInitiateRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/ambassadors'
    | '/auth'
    | '/contact'
    | '/events'
    | '/organizers'
    | '/events/$eventId'
    | '/ticket/$bookingId'
    | '/api/events'
    | '/api/bookings'
    | '/api/bookings/$bookingId'
    | '/api/mpesa/initiate'
    | '/api/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/ambassadors'
    | '/auth'
    | '/contact'
    | '/events'
    | '/organizers'
    | '/events/$eventId'
    | '/ticket/$bookingId'
    | '/api/events'
    | '/api/bookings'
    | '/api/bookings/$bookingId'
    | '/api/mpesa/initiate'
    | '/api/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/ambassadors'
    | '/auth'
    | '/contact'
    | '/events'
    | '/organizers'
    | '/events/$eventId'
    | '/ticket/$bookingId'
    | '/api/events'
    | '/api/bookings'
    | '/api/bookings/$bookingId'
    | '/api/mpesa/initiate'
    | '/api/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  OrganizersRoute: typeof OrganizersRoute
  TicketBookingIdRoute: typeof TicketBookingIdRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiBookingsBookingIdRoute: typeof ApiBookingsBookingIdRoute
  ApiMpesaInitiateRoute: typeof ApiMpesaInitiateRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$bookingId': {
      id: '/ticket/$bookingId'
      path: '/ticket/$bookingId'
      fullPath: '/ticket/$bookingId'
      preLoaderRoute: typeof TicketBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$bookingId': {
      id: '/api/bookings/$bookingId'
      path: '/api/bookings/$bookingId'
      fullPath: '/api/bookings/$bookingId'
      preLoaderRoute: typeof ApiBookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/initiate': {
      id: '/api/mpesa/initiate'
      path: '/api/mpesa/initiate'
      fullPath: '/api/mpesa/initiate'
      preLoaderRoute: typeof ApiMpesaInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  OrganizersRoute: OrganizersRoute,
  TicketBookingIdRoute: TicketBookingIdRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiBookingsBookingIdRoute: ApiBookingsBookingIdRoute,
  ApiMpesaInitiateRoute: ApiMpesaInitiateRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
